server:
  port: ${PORT:${SERVER_PORT:0}}


info:
  id: ${spring.application.name}
  
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
